# Data Cleaning
- 대상파일: "api_data_XXX.csv"
- url: 중복되는 값만 제거하는 것으로 처리
- title: url 중복제거 후 title이 중복된다면 제거(거의 abstract, step_content, referecnce …등 데이터가 완전히 일치함)
- abstract: “””” 등 여러개가 있는 경우 “ 한개로 변환 => replace이용, 띄어쓰기 2칸이상 들여쓰기 제거(예: “””summary: ⇒ “summary: ), \n, \t 등 특수 문자 제거(내용에 직접 기입된 것), enter가 두 번 입력된것(python print시 “\n\n”로 표시)는 enter 한 번 입력된 것으로 변경(replace(“\n\n, \n”)이용)
- step_content: 띄어쓰기가 2번이상 연속으로 된경우 띄어쓰기 한칸으로 처리, \n, \t 등 특수문자 제거(내용에 직접 기입된 것), <no data>포함된 데이터에서 다른 데이터가 있다면 <no data>제거 => <no data>를 일괄제거하는 것으로 해결가능(데이터가 없다면 빈칸), ‘\u003e’, ‘\u003c’와 같은 ‘\uXXX ‘형식의 키워드를 제거해야함
- reference: <no data>가 대부분 => <no data> 무조건 삭제, 따옴표 제거시 비어있다면 <no data>와 동일하게 처리됨(예: “ , “”, “” “”” “”) => 영어 알파벳 및 숫자가 포함되지 않는 경우에 해당
- guidelines: 상기의 step_content와 비슷함, 따옴표 제거 필요, NA(no data와 비슷함) => 제거
- materials: NA => 제거, <no data>나 length가 0인 경우 빈 데이터 처리(null 처리), 따옴표 연속2개이상인 경우 1개로 수정
- 공통사항: <no data>제거, 따옴표 여러개 있는 경우 하나로 수정, \n \t \uXXX 등 특수문자 제거, NA제거, 띄어쓰기 2칸이상 1칸으로 처리, 데이터 없음 => null로처리

# 대상 파일 지정

In [1]:
# jupyter에서의 전처리는 하나의 파일로 진행 => 전처리 통합본은 py파일로 만들며, 모든 대상 파일로 함
import pandas as pd

df = pd.read_csv("api_data_DNA.csv")
df

,url,title,abstract,step_content,reference,guidelines,materials
0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Us...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,Materials: %s%s Product Vendor Cat # Sucro...,MATERIALS Lysozyme from chicken egg white Merc...
4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...
2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer ...
2787,https://www.protocols.io/view/ucsf-cat-covid-1...,UCSF CAT COVID-19 Tailed 275bp v3 ARTIC protoc...,This is a tailed amplicon method similar to ht...,Important! This step must be performed in a RN...,<no data>,It is vital cDNA setup is performed in a labor...,LunaScript RT SuperMix Kit New England Biolab...
2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

# URL 중복 제거

In [2]:
# url 중복확인
len(df["url"].unique())

2412

In [3]:
# url 중복제거 후 테이블
df = df.drop_duplicates(subset="url", keep="first").reset_index()
df = df.rename(columns={'index': 'protocol_id'})
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Us...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,Materials: %s%s Product Vendor Cat # Sucro...,MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2407,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2408,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer ...
2409,2787,https://www.protocols.io/view/ucsf-cat-covid-1...,UCSF CAT COVID-19 Tailed 275bp v3 ARTIC protoc...,This is a tailed amplicon method similar to ht...,Important! This step must be performed in a RN...,<no data>,It is vital cDNA setup is performed in a labor...,LunaScript RT SuperMix Kit New England Biolab...
2410,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2411,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

# TITLE 중복 제거

In [4]:
# title 중복 확인
len(df["title"].unique())

2347

In [5]:
# title 중복제거 후 테이블
df = df.drop_duplicates(subset="title", keep="first").reset_index()
df = df.drop(columns=['index'])
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Us...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,Materials: %s%s Product Vendor Cat # Sucro...,MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,<no data>,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer ...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

# 각 요소별 text 전처리

- “””” 등 여러개가 있는 경우 “ 한개로 변환

In [6]:
df = df.replace(r'"+', '"', regex=True)
df = df.replace(r'" ', '', regex=True)

In [7]:
# 전처리 후 확인
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Us...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,Materials: %s%s Product Vendor Cat # Sucro...,MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,<no data>,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer ...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

In [8]:
# 띄어쓰기 2칸이상 들여쓰기 제거
df = df.replace(r'\s{2,}', ' ', regex=True)
df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)
df

C:\Users\Playdata\AppData\Local\Temp\ipykernel_10820\735188079.py:3: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,<no data>,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

- 특수 문자 제거(내용에 직접 기입된 것)

In [9]:
df = df.replace(r"\t", "", regex=True)
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,<no data>,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

- enter가 두 번 입력된것

In [10]:
df = df.replace(r'\n+', '\n', regex=True)
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,<no data>,"Create mixture of CsCl, Proteinase K, and SDS....",<no data>,This protocol comes from a group of other prot...,<no data>
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,<no data>,"Add 2 volumes of ice cold ethanol, mix well.Le...",<no data>,This protocol comes from a group of other prot...,<no data>
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,<no data>,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,<no data>,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,<no data>,Thaw sterivex filters on ice.Add 40µL lysozyme...,<no data>,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,<no data>,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,<no data>,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,<no data>,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,<no data>,PCR reactions performed on BioRad QX200 Drople...

- 문자열 "\<no data\>" 제거

In [11]:
df = df.replace("<no data>", "")
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,,"Create mixture of CsCl, Proteinase K, and SDS....",,This protocol comes from a group of other prot...,
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,,"Add 2 volumes of ice cold ethanol, mix well.Le...",,This protocol comes from a group of other prot...,
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,,Thaw sterivex filters on ice.Add 40µL lysozyme...,,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,,PCR reactions performed on BioRad QX200 Drople...

-  ‘\u003e’, ‘\u003c’와 같은 ‘\uXXX ‘형식의 키워드를 제거

In [12]:
df = df.replace(r"\\u[0-9a-fA-F]{4}", "", regex=True)
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,,"Create mixture of CsCl, Proteinase K, and SDS....",,This protocol comes from a group of other prot...,
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,,"Add 2 volumes of ice cold ethanol, mix well.Le...",,This protocol comes from a group of other prot...,
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,,Thaw sterivex filters on ice.Add 40µL lysozyme...,,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,,PCR reactions performed on BioRad QX200 Drople...

- “ , “”, “” “”” “”와 같이 따옴표외 문자 및 숫자가 없는 경우 => 빈 데이터 처리

In [13]:
# 따옴표만 있거나 공백만 있는 경우 NaN으로 변환
df = df.replace(r'^\s*["“”\'’]*\s*$', "", regex=True)
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,,"Create mixture of CsCl, Proteinase K, and SDS....",,This protocol comes from a group of other prot...,
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,,"Add 2 volumes of ice cold ethanol, mix well.Le...",,This protocol comes from a group of other prot...,
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,,Thaw sterivex filters on ice.Add 40µL lysozyme...,,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,,PCR reactions performed on BioRad QX200 Drople...

- "NA"(no data와 비슷함) => 제거

In [14]:
df = df.replace("NA", "")
df

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,,"Create mixture of CsCl, Proteinase K, and SDS....",,This protocol comes from a group of other prot...,
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,,"Add 2 volumes of ice cold ethanol, mix well.Le...",,This protocol comes from a group of other prot...,
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,,Thaw sterivex filters on ice.Add 40µL lysozyme...,,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,,PCR reactions performed on BioRad QX200 Drople...

# 데이터 값이 없는 경우(띄어쓰기만 있는 것도 포함)
- RDB 및 VectorDB 도입을 고려해야함
- 데이터 값이 없는 경우 null처리 => vectorDB에서 null 임베딩 오류 발생 => 권장하지 않음
- 데이터 값이 없는 경우 빈 문자열 처리 => 의미 없는 벡터 생성 => 결과 품질 저하
- 데이터 값이 없는 경우 "\<no data\>" 삽입(Placeholder) => \<no data\> 임베딩은 의미 없는 벡터 => semantic search에서 다른 쿼리와 거의 관계 없는 결과로 노이즈 발생 => 여러 문서가 \<no data\>이면 벡터들이 서로 비슷하게 만들어져 검색 결과가 섞임

- 결론: 데이터 값이 없는 경우 빈 문자열("")로 처리 => VectorDB 구축시 이를 어떻게 처리할지 고려 필요

In [15]:
# NaN을 빈 문자열로 변경
df = df.fillna("")

# 공백만 있는 문자열을 빈 문자열로 변경
df = df.applymap(lambda x: "" if isinstance(x, str) and x.strip() == "" else x)
df

C:\Users\Playdata\AppData\Local\Temp\ipykernel_10820\1698802205.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df = df.applymap(lambda x: "" if isinstance(x, str) and x.strip() == "" else x)

,protocol_id,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/DNA-Extraction-P...,DNA Extraction Protocol,,"Create mixture of CsCl, Proteinase K, and SDS....",,This protocol comes from a group of other prot...,
1,1,https://www.protocols.io/view/DNA-Precipitatio...,DNA Precipitation Protocol,,"Add 2 volumes of ice cold ethanol, mix well.Le...",,This protocol comes from a group of other prot...,
2,2,https://www.protocols.io/view/Cesium-Chloride-...,Cesium Chloride Protocol for Phage,This protocol contains 4 sections: 1. Cesium C...,Filter cesium solutions with 0.02µm filter Use...,,Needed:Cesium solutions0.02 µm filterCsClTubes...,MATERIALS SW41 Ti (with Beckman Ultra) Swingin...
3,3,https://www.protocols.io/view/DNA-Extraction-f...,DNA Extraction from sorted cells,"Modified after V. Rich, 2/10/07: DNA extractio...",Prepare 2x lysis buffer and add to the volume ...,,"Materials: %s%s Product Vendor Cat # Sucrose, ...",MATERIALS Lysozyme from chicken egg white Merc...
4,4,https://www.protocols.io/view/DNA-RNA-Extracti...,DNA/RNA Extractions from Sterivex Filters,,Thaw sterivex filters on ice.Add 40µL lysozyme...,,2.0 mL Lysis Buffer is added to Sterivex immed...,STEP MATERIALS Chloroform:IAA Abblis Catalog #...
...,...,...,...,...,...,...,...,...
2342,2784,https://www.protocols.io/view/t7-in-vitro-mrna...,T7 In Vitro mRNA Synthesis with Separate Cappi...,This protocol describes the stepwise synthesis...,Assess the target sequence to ensure proper pl...,,"Always work in a clean, RNase-free environment...",1. DNA Template PreparationQ5 High-Fidelity 2X...
2343,2785,https://www.protocols.io/view/qpcr-assay-for-t...,qPCR assay for the Detection of Coralliophila ...,This real-time PCR assay is designed to detect...,Remove PCR reagents from the freezer and allow...,Coralliophila galea voucher MNHN-IM-2013-9565 ...,Primer storage: Keep at -20 °C for long-term s...,Primers :*Only one primer set is required for ...
2344,2786,https://www.protocols.io/view/dna-isolation-fr...,DNA Isolation from EDTA-blood,Whole blood collected in EDTA vials (9-10mL) i...,Discard supernatant (in sink) and put the Falc...,,"All research must adhere to the current, updat...",Erylysis-Buffer NH4Cl (molecular weight 53.49)...
2345,2788,https://www.protocols.io/view/whole-genome-dna...,Whole-Genome DNA Extractions for MinION Sequen...,Long-read sequencing is increasingly accessibl...,Grow strains on Petri dishes with PDA medium f...,,18. Precipitate the DNA by adding 3.5 mL isopr...,Fungal sample preparation:- Petri dishes with ...
2346,2789,https://www.protocols.io/view/quantification-o...,Quantification of DNA Targets by Droplet Digit...,Quantification of DNA targets by Droplet Digit...,"Once all components have thawed, mix through a...",Original Source of PCR assays:Salmonella (invA...,,PCR reactions performed on BioRad QX200 Drople...

# 전처리 결과를 확인할 수 있게 csv파일로 생성

In [16]:
df.to_csv(f"cleaned_data_DNA.csv", index=False)