# section_category가 result인 데이터만 다른이름의 csv로 저장하기

In [1]:
import pandas as pd

df = pd.read_csv("raw_dataset_reference.csv")
df.head(10)

,section_id,pmid,topic_category,section_title,section_text,path,section_category,article_category,fig_ids,table_ids
0,38598310_sec1,38598310,Protein Structure & Enzyme Engineering,Introduction,"The “sunshine vitamin”, vitamin D3(VitD3), is ...",Introduction,introduction,research,161183008895;384174878961;470307513129,NaN
1,38598310_sec4,38598310,Protein Structure & Enzyme Engineering,Conformational Search,All stationary-point geometries(equilibrium co...,Calculation Method > Conformational Search,method,research,678947196634,NaN
2,38598310_sec8,38598310,Protein Structure & Enzyme Engineering,Accessible Conformers,Based on the findings from Furche and co-worke...,Results and Discussion > Accessible Conformers,result,research,683438586433,NaN
3,38598310_sec9,38598310,Protein Structure & Enzyme Engineering,Conformational Analysis,The conformational exploration using TorsiFlex...,Results and Discussion > Conformational Analysis,result,research,426700642544;798125557350,NaN
4,38598310_sec10,38598310,Protein Structure & Enzyme Engineering,Thermal Rate Constants and Catalytic Effect,Our MD simulations show that all conformers mu...,Results and Discussion > Thermal Rate Constant...,result,research,210276443294,tbl1
5,36779817_sec4,36779817,Protein Structure & Enzyme Engineering,FUNCTIONAL ROLE OF FOLDING INTERMEDIATE IN PRO...,4 Serpins(serine protease inhibitors) provide ...,FUNCTIONAL ROLE OF FOLDING INTERMEDIATE IN PRO...,main,review,953571766348,NaN
6,36779817_sec6,36779817,Protein Structure & Enzyme Engineering,PHARMACOLOGICAL VALUE OF TARGETING FOLDING INT...,6 Conventional rational drug discovery is prim...,PHARMACOLOGICAL VALUE OF TARGETING FOLDING INT...,main,review,282551023184,NaN
7,40919504_sec2,40919504,Protein Structure & Enzyme Engineering,Measuring stability,2 Many single-domain globular proteins undergo...,Measuring stability,main,review,128964201360,NaN
8,39739814_sec2,39739814,Protein Structure & Enzyme Engineering,Identification of MALT1 as a Modulator of GPX4...,To evaluate the potential of leveraging ferrop...,Results > Identification of MALT1 as a Modulat...,result,research,276749254860,NaN
9,39739814_sec3,39739814,Protein Structure & Enzyme Engineering,MALT1 Stabilizes GPX4 through Cleavage of E3 U...,To investigate the mechanisms by which MALT1 r...,Results > MALT1 Stabilizes GPX4 through Cleava...,result,research,145411149905,NaN

In [2]:
result_df = df[df["section_category"] == "result"].copy()
result_df.head(10)

,section_id,pmid,topic_category,section_title,section_text,path,section_category,article_category,fig_ids,table_ids
2,38598310_sec8,38598310,Protein Structure & Enzyme Engineering,Accessible Conformers,Based on the findings from Furche and co-worke...,Results and Discussion > Accessible Conformers,result,research,683438586433,NaN
3,38598310_sec9,38598310,Protein Structure & Enzyme Engineering,Conformational Analysis,The conformational exploration using TorsiFlex...,Results and Discussion > Conformational Analysis,result,research,426700642544;798125557350,NaN
4,38598310_sec10,38598310,Protein Structure & Enzyme Engineering,Thermal Rate Constants and Catalytic Effect,Our MD simulations show that all conformers mu...,Results and Discussion > Thermal Rate Constant...,result,research,210276443294,tbl1
8,39739814_sec2,39739814,Protein Structure & Enzyme Engineering,Identification of MALT1 as a Modulator of GPX4...,To evaluate the potential of leveraging ferrop...,Results > Identification of MALT1 as a Modulat...,result,research,276749254860,NaN
9,39739814_sec3,39739814,Protein Structure & Enzyme Engineering,MALT1 Stabilizes GPX4 through Cleavage of E3 U...,To investigate the mechanisms by which MALT1 r...,Results > MALT1 Stabilizes GPX4 through Cleava...,result,research,145411149905,NaN
10,39739814_sec4,39739814,Protein Structure & Enzyme Engineering,MALT1 Inhibition Triggers Ferroptosis in Liver...,The crucial regulatory role of the MALT1–RC3H1...,Results > MALT1 Inhibition Triggers Ferroptosi...,result,research,614429346520,NaN
11,39739814_sec5,39739814,Protein Structure & Enzyme Engineering,MALT1 Inhibitor Down-Regulates GPX4 through Ub...,Quantitative proteomics analysis revealed that...,Results > MALT1 Inhibitor Down-Regulates GPX4 ...,result,research,245734622300,NaN
12,39739814_sec6,39739814,Protein Structure & Enzyme Engineering,MALT1 Inhibition Is Synergistic with Sorafenib...,Given that many liver cancer cell lines demons...,Results > MALT1 Inhibition Is Synergistic with...,result,research,659650355594,NaN
13,39742998_sec2,39742998,Protein Structure & Enzyme Engineering,H80 and E166 are essential for RNase J2 activity,The active site of RNase J2 has a single metal...,Results > H80 and E166 are essential for RNase...,result,research,497300792137,NaN
14,39742998_sec4,39742998,Protein Structure & Enzyme Engineering,Influence of the active site dynamics on RNase...,The RT-FeDEx assay revealed an unanticipated f...,Results > Influence of the active site dynamic...,result,research,356948113015,NaN

In [3]:
result_df.to_csv("section_category_result.csv", index=False)

# 데이터 추가

In [16]:
import pandas as pd

df_3 = pd.read_csv("sectionS_3.csv")
df_3.head(5)

# section_category의 고유값 확인 (문제 진단용)
print("=== section_category 고유값 확인 ===")
print(df_3["section_category"].value_counts())
print("\n=== 고유값 리스트 ===")
print(df_3["section_category"].unique())
print("\n=== 데이터 타입 ===")
print(df_3["section_category"].dtype)
print("\n=== NaN 개수 ===")
print(df_3["section_category"].isna().sum())

=== section_category 고유값 확인 ===
section_category
method          33008
result          19518
discussion       6361
main             5574
other            5032
introduction     4613
abstract         4184
Name: count, dtype: int64

=== 고유값 리스트 ===
['abstract' 'introduction' 'method' 'result' 'discussion' 'other' 'main']

=== 데이터 타입 ===
object

=== NaN 개수 ===
0

In [17]:
# section_category 정제: 공백 제거 및 소문자 변환
df_3["section_category_cleaned"] = df_3["section_category"].astype(str).str.strip().str.lower()

# 정제된 값 확인
print("=== 정제 후 section_category 고유값 ===")
print(df_3["section_category_cleaned"].value_counts())

# "result"로 필터링 (공백 제거 및 소문자 변환 후)
result_df_3 = df_3[df_3["section_category_cleaned"] == "result"].copy()

# 원본 section_category 컬럼만 유지 (cleaned 컬럼 제거)
result_df_3 = result_df_3.drop(columns=["section_category_cleaned"])

print(f"\n필터링된 데이터 개수: {len(result_df_3)}")

# 정말로 "result"만 남았는지 확인
if len(result_df_3) > 0:
    unique_values = result_df_3["section_category"].unique()
    print(f"\n필터링 후 고유값: {unique_values}")
    
    # 공백 제거 후 소문자로 변환해서 "result"와 비교
    cleaned_values = [str(v).strip().lower() for v in unique_values]
    non_result = [v for v, c in zip(unique_values, cleaned_values) if c != "result"]
    
    if non_result:
        print(f"⚠️ 경고: 'result'가 아닌 값 발견: {non_result}")
        # "result"가 아닌 행 제거
        result_df_3 = result_df_3[
            result_df_3["section_category"].astype(str).str.strip().str.lower() == "result"
        ].copy()
        print(f"정제 후 데이터 개수: {len(result_df_3)}")
    else:
        print("✅ 모든 값이 'result'입니다.")
else:
    print("⚠️ 경고: 필터링된 데이터가 없습니다!")

# 최종 저장
result_df_3.to_csv("section_category_result_3.csv", index=False)
print(f"\n✅ 저장 완료: section_category_result_3.csv ({len(result_df_3)}개 행)")

=== 정제 후 section_category 고유값 ===
section_category_cleaned
method          33008
result          19518
discussion       6361
main             5574
other            5032
introduction     4613
abstract         4184
Name: count, dtype: int64

필터링된 데이터 개수: 19518

필터링 후 고유값: ['result']
✅ 모든 값이 'result'입니다.

✅ 저장 완료: section_category_result_3.csv (19518개 행)

In [6]:
import pandas as pd

df_3 = pd.read_csv("sections_3.csv")
df_3.head(5)

# section_category의 고유값 확인 (문제 진단용)
print("=== section_category 고유값 확인 ===")
print(df_3["section_category"].value_counts())
print("\n=== 고유값 리스트 ===")
print(df_3["section_category"].unique())

,section_id,pmid,topic_category,section_title,section_text,path,section_category,article_category,fig_ids,table_ids
0,41257248_sec0,41257248,mRNA Therapeutics & LNP Delivery,Abstract,AbstractBabies born prematurely with gestation...,abstract,abstract,research,NaN,NaN
1,41257248_sec1,41257248,mRNA Therapeutics & LNP Delivery,Introduction,"New RNA capturing, sequencing, and annotative ...",Introduction,introduction,research,NaN,NaN
2,41257248_sec3,41257248,mRNA Therapeutics & LNP Delivery,Animals and BPD model,Wildtype C57BL/6 mice(males and females) were ...,Materials and methods > Animals and BPD model,method,research,NaN,NaN
3,41257248_sec4,41257248,mRNA Therapeutics & LNP Delivery,Human tissues,Two cohorts of de-identified postmortem lung t...,Materials and methods > Human tissues,method,research,NaN,NaN
4,41257248_sec5,41257248,mRNA Therapeutics & LNP Delivery,RNA extraction,Neonatal mouse lungs were harvested from four ...,Materials and methods > RNA extraction,method,research,NaN,NaN

In [ ]:
result_df_3 = df_3[df_3["section_category"] == "result"].copy()
result_df_3.to_csv("section_category_result_3.csv", index=False)

# 3개 csv파일 순서대로 합치기

In [19]:
import pandas as pd

# 인코딩을 자동으로 감지하는 함수
def read_csv_with_encoding(filepath):
    """여러 인코딩을 시도해서 CSV 파일 읽기"""
    encodings = ['utf-8', 'utf-8-sig', 'cp949', 'euc-kr', 'latin-1', 'iso-8859-1', 'windows-1252']
    
    for encoding in encodings:
        try:
            df = pd.read_csv(filepath, encoding=encoding)
            print(f"✅ {filepath}: {encoding} 인코딩으로 성공적으로 읽음")
            return df
        except UnicodeDecodeError:
            continue
        except Exception as e:
            print(f"⚠️ {filepath}: {encoding} 인코딩 시도 중 오류: {e}")
            continue
    
    # 모든 인코딩 실패 시 에러 발생
    raise ValueError(f"모든 인코딩 시도 실패: {filepath}")

# 각 CSV 파일 불러오기
print("CSV 파일 읽기 시작...\n")
df_1 = read_csv_with_encoding("section_category_result_1.csv")
df_2 = read_csv_with_encoding("section_category_result_2.csv")
df_3 = read_csv_with_encoding("section_category_result_3.csv")

print(f"\n데이터 개수:")
print(f"  df_1: {len(df_1)}개")
print(f"  df_2: {len(df_2)}개")
print(f"  df_3: {len(df_3)}개")

# 순서대로 합치기
merged_df = pd.concat([df_1, df_2, df_3], ignore_index=True)

print(f"\n합쳐진 데이터 개수: {len(merged_df)}개")

# 합쳐진 결과 확인
print("\n합쳐진 데이터 미리보기:")
print(merged_df.head())

# 합쳐진 데이터 저장 (UTF-8로 저장)
merged_df.to_csv("section_category_result_merged.csv", index=False, encoding='utf-8-sig')
print(f"\n✅ 저장 완료: section_category_result_merged.csv ({len(merged_df)}개 행)")

CSV 파일 읽기 시작...

✅ section_category_result_1.csv: utf-8 인코딩으로 성공적으로 읽음
✅ section_category_result_2.csv: latin-1 인코딩으로 성공적으로 읽음
✅ section_category_result_3.csv: latin-1 인코딩으로 성공적으로 읽음

데이터 개수:
  df_1: 2702개
  df_2: 10627개
  df_3: 19494개

합쳐진 데이터 개수: 32823개

합쳐진 데이터 미리보기:
       section_id      pmid                          topic_category  \
0   38598310_sec8  38598310  Protein Structure & Enzyme Engineering
1   38598310_sec9  38598310  Protein Structure & Enzyme Engineering
2  38598310_sec10  38598310  Protein Structure & Enzyme Engineering
3   39739814_sec2  39739814  Protein Structure & Enzyme Engineering
4   39739814_sec3  39739814  Protein Structure & Enzyme Engineering

                                       section_title  \
0                              Accessible Conformers
1                            Conformational Analysis
2        Thermal Rate Constants and Catalytic Effect
3  Identification of MALT1 as a Modulator of GPX4...
4  MALT1 Stabilizes GPX4 through Cleavage of E3 U...

                                        section_text  \
0  Based on the findings from Furche and co-worke...
1  The conformational exploration using TorsiFlex...
2  Our MD simulations show that all conformers mu...
3  To evaluate the potential of leveraging ferrop...
4  To investigate the mechanisms by which MALT1 r...

                                                path section_category  \
0     Results and Discussion > Accessible Conformers           result
1   Results and Discussion > Conformational Analysis           result
2  Results and Discussion > Thermal Rate Constant...           result
3  Results > Identification of MALT1 as a Modulat...           result
4  Results > MALT1 Stabilizes GPX4 through Cleava...           result

  article_category                    fig_ids table_ids
0         research               683438586433       NaN
1         research  426700642544;798125557350       NaN
2         research               210276443294      tbl1
3         research               276749254860       NaN
4         research               145411149905       NaN

✅ 저장 완료: section_category_result_merged.csv (32823개 행)

# final_*.jsonl 파일 합치기

In [23]:
import glob
import os
from datetime import datetime
from pathlib import Path

# 절대 경로 직접 사용
root_dir = r"c:\dev\ai_camp\SKN18-FINAL-2TEAM\sllm\datasets\generated"

print(f"📂 검색 디렉토리: {root_dir}")
print(f"   존재 여부: {os.path.exists(root_dir)}")

# 경로 보정: 상대경로는 현재 작업 디렉터리 기준이므로, 먼저 디렉터리 존재 확인 및 생성
if not os.path.exists(root_dir):
    print(f"⚠️ 디렉토리가 존재하지 않습니다: {root_dir}")
    os.makedirs(root_dir, exist_ok=True)

# 최종 파일 패턴 설정
jsonl_files = sorted(
    glob.glob(os.path.join(root_dir, "final_*.jsonl"))
)

if not jsonl_files:
    print(f"⚠️ 합칠 final_*.jsonl 파일이 '{os.path.abspath(root_dir)}'에 없습니다.")
    print(f"   디렉토리 내용:")
    if os.path.exists(root_dir):
        files = os.listdir(root_dir)
        jsonl_in_dir = [f for f in files if f.endswith('.jsonl')]
        if jsonl_in_dir:
            print(f"   JSONL 파일들: {jsonl_in_dir[:10]}...")  # 처음 10개만 표시
        else:
            print(f"   (JSONL 파일 없음)")
    print("   병합을 건너뜁니다.")
else:
    # 출력 파일명 (타임스탬프 포함)
    output_file = os.path.join(root_dir, f'final_sft_dataset_merged_{datetime.now().strftime("%Y%m%d_%H%M%S")}.jsonl')

    print(f"합칠 파일 목록 ({len(jsonl_files)}개):")
    for f in jsonl_files:
        file_size = os.path.getsize(f) if os.path.exists(f) else 0
        print(f"  - {os.path.basename(f)} ({file_size:,} bytes)")

    try:
        total_lines = 0
        with open(output_file, 'w', encoding='utf-8') as outfile:
            for fname in jsonl_files:
                if not os.path.exists(fname):
                    print(f"⚠️ {fname} 파일이 존재하지 않습니다. 건너뜁니다.")
                    continue
                with open(fname, 'r', encoding='utf-8') as infile:
                    for line in infile:
                        if line.strip():  # 빈 줄 제외
                            outfile.write(line)
                            total_lines += 1
        print(f"\n✅ {os.path.basename(output_file)} 에 {len(jsonl_files)}개 파일이 성공적으로 합쳐졌습니다.")
        print(f"   총 {total_lines:,}개 라인")
    except Exception as e:
        print(f"❌ 병합 중 오류 발생: {e}")
        import traceback
        traceback.print_exc()

📂 검색 디렉토리: c:\dev\ai_camp\SKN18-FINAL-2TEAM\sllm\datasets\generated
   존재 여부: True
합칠 파일 목록 (5개):
  - final_sft_dataset_251230_1448.jsonl (2,084,104 bytes)
  - final_sft_dataset_251231_0744.jsonl (3,363,973 bytes)
  - final_sft_dataset_251231_0856.jsonl (131,775 bytes)
  - final_sft_dataset_251231_1004.jsonl (1,048,327 bytes)
  - final_sft_dataset_251231_1101.jsonl (371,669 bytes)

✅ final_sft_dataset_merged_20251231_114541.jsonl 에 5개 파일이 성공적으로 합쳐졌습니다.
   총 3,254개 라인

In [24]:
# 합쳐진 JSONL에서 중복 데이터(예: 완전 동일한 입력/출력 샘플) 제거

import json

deduped_output_file = os.path.splitext(output_file)[0] + "_deduped.jsonl"

seen = set()
deduped_lines = 0
try:
    with open(output_file, 'r', encoding='utf-8') as infile, \
         open(deduped_output_file, 'w', encoding='utf-8') as outfile:
        for idx, line in enumerate(infile):
            line = line.rstrip('\n\r')
            if not line:
                continue
            try:
                obj = json.loads(line)
            except Exception as e:
                print(f"⚠️ {idx+1}번째 줄 JSON 파싱 오류: {e}")
                continue
            # 입력(input)과 출력(output)이 완전히 동일한 샘플 중복 방지
            # (딕셔너리는 JSON 포맷의 문자열로 변환해서 비교)
            key = json.dumps(obj.get("input", {}), sort_keys=True) + "::" + json.dumps(obj.get("output", {}), sort_keys=True)
            if key in seen:
                continue
            seen.add(key)
            outfile.write(json.dumps(obj, ensure_ascii=False) + "\n")
            deduped_lines += 1
    print(f"🚮 중복 제거 완료: {deduped_output_file}")
    print(f"   {deduped_lines:,}개 라인 (중복 제외)")
except Exception as e:
    print(f"❌ 중복 제거 중 오류 발생: {e}")
    import traceback
    traceback.print_exc()

🚮 중복 제거 완료: c:\dev\ai_camp\SKN18-FINAL-2TEAM\sllm\datasets\generated\final_sft_dataset_merged_20251231_114541_deduped.jsonl
   3,254개 라인 (중복 제외)