# 대상 파일: api_data_Cell.csv

In [1]:
import pandas as pd

df = pd.read_csv("api_data_Cell.csv")
df

,url,title,abstract,step_content,reference,guidelines,materials
0,https://www.protocols.io/view/ventral-midbrain...,Ventral midbrain dopaminergic (mDA) Neuron Dif...,Generating authentic functional ventral midbr...,PSC cultures should be completely undifferenti...,"Kim TW, Piao J, Koo SY, Kriks S, Chung SY, Bet...",Day -X: PSC expansion iPSC are cultured follo...,%s%s
1,https://www.protocols.io/view/transformation-p...,Transformation Protocol for Targeted Homologou...,Detailed instructions for the introduction of ...,Digest 100 µg of plasmid construct in 750 µL ...,1. Moseley et al. Production of lipids and ter...,<no data>,Auxenochlorella protothecoides cells1.5 mL Gra...
2,https://www.protocols.io/view/an-end-to-end-wo...,An end-to-end workflow for GD2 immunofluoresce...,This protocol allows the staining of the membr...,2% FCS/1% BSA - washing buffer preparation:Dis...,<no data>,The protocol was developed according to the Or...,Plastic/metallic warePipette tips for battery-...
3,https://www.protocols.io/view/optimizing-genet...,Optimizing Genetic Modification in Agrobacteri...,Electroporation has emerged as a highly effect...,Begin by inoculating 10 ml of LB medium with a...,"Kámán-Tóth E, Pogány M, Dankó T, Szatmári Á, B...",<no data>,Reagents:LB medium Kanamicyn 50 mg/mlSterile 1...
4,https://www.protocols.io/view/multi-seq-barcod...,MULTI-Seq Barcoding and Library Preparation,This protocol describes MULTI-Seq barcoding of...,Oligonucleotides (store in -20°C for large ter...,"McGinnis CS, Patterson DM, Winkler J, Conrad D...",<no data>,Reagents:%s%s
...,...,...,...,...,...,...,...
4985,https://www.protocols.io/view/transmission-ele...,Transmission electron microscopy of fibroblasts,This protocol describes the procedure for prep...,Fix cells by replacing the growth medium with ...,<no data>,<no data>,<no data>
4986,https://www.protocols.io/view/scqers-library-p...,scQers library preparation,The inability to scalably and precisely measur...,"For single-cell reporters, three libraries are...",<no data>,<no data>,<no data>
4987,https://www.protocols.io/view/scatac-seq-on-me...,scATAC-seq on mEBs,The inability to scalably and precisely measur...,Single-nuclei preparation for scATAC-seq were ...,<no data>,<no data>,<no data>
4988,https://www.protocols.io/view/protocol-for-mai...,Protocol for Maintaining iPSC Cultures,"Protocols for passaging, maintaining, freezing...",Coat desired wells or cell culture dish with M...,"Chen Y, Tristan CA, Chen L, Jovanovic VM, Mall...",Feeding scheduleCells are fed with iPS-Brew me...,Reagents for iPS culture:- StemMACS™ iPS-Brew ...
4989,https://www.protocols.io/view/preparation-of-s...,Preparation of single-cell suspension from mou...,Preparation of single-cell suspension from mou...,Finely dissect the pancreas into small fragmen...,<no data>,1. Finely dissect the pancreas into small frag...,Pancreas tissue; blade (for dissection); Colla...

# dataframe의 좌측 숫자를 "protocol_id"로 설정

In [2]:
df = df.reset_index().rename(columns={'index': 'protocol_sid'})
df

,protocol_sid,url,title,abstract,step_content,reference,guidelines,materials
0,0,https://www.protocols.io/view/ventral-midbrain...,Ventral midbrain dopaminergic (mDA) Neuron Dif...,Generating authentic functional ventral midbr...,PSC cultures should be completely undifferenti...,"Kim TW, Piao J, Koo SY, Kriks S, Chung SY, Bet...",Day -X: PSC expansion iPSC are cultured follo...,%s%s
1,1,https://www.protocols.io/view/transformation-p...,Transformation Protocol for Targeted Homologou...,Detailed instructions for the introduction of ...,Digest 100 µg of plasmid construct in 750 µL ...,1. Moseley et al. Production of lipids and ter...,<no data>,Auxenochlorella protothecoides cells1.5 mL Gra...
2,2,https://www.protocols.io/view/an-end-to-end-wo...,An end-to-end workflow for GD2 immunofluoresce...,This protocol allows the staining of the membr...,2% FCS/1% BSA - washing buffer preparation:Dis...,<no data>,The protocol was developed according to the Or...,Plastic/metallic warePipette tips for battery-...
3,3,https://www.protocols.io/view/optimizing-genet...,Optimizing Genetic Modification in Agrobacteri...,Electroporation has emerged as a highly effect...,Begin by inoculating 10 ml of LB medium with a...,"Kámán-Tóth E, Pogány M, Dankó T, Szatmári Á, B...",<no data>,Reagents:LB medium Kanamicyn 50 mg/mlSterile 1...
4,4,https://www.protocols.io/view/multi-seq-barcod...,MULTI-Seq Barcoding and Library Preparation,This protocol describes MULTI-Seq barcoding of...,Oligonucleotides (store in -20°C for large ter...,"McGinnis CS, Patterson DM, Winkler J, Conrad D...",<no data>,Reagents:%s%s
...,...,...,...,...,...,...,...,...
4985,4985,https://www.protocols.io/view/transmission-ele...,Transmission electron microscopy of fibroblasts,This protocol describes the procedure for prep...,Fix cells by replacing the growth medium with ...,<no data>,<no data>,<no data>
4986,4986,https://www.protocols.io/view/scqers-library-p...,scQers library preparation,The inability to scalably and precisely measur...,"For single-cell reporters, three libraries are...",<no data>,<no data>,<no data>
4987,4987,https://www.protocols.io/view/scatac-seq-on-me...,scATAC-seq on mEBs,The inability to scalably and precisely measur...,Single-nuclei preparation for scATAC-seq were ...,<no data>,<no data>,<no data>
4988,4988,https://www.protocols.io/view/protocol-for-mai...,Protocol for Maintaining iPSC Cultures,"Protocols for passaging, maintaining, freezing...",Coat desired wells or cell culture dish with M...,"Chen Y, Tristan CA, Chen L, Jovanovic VM, Mall...",Feeding scheduleCells are fed with iPS-Brew me...,Reagents for iPS culture:- StemMACS™ iPS-Brew ...
4989,4989,https://www.protocols.io/view/preparation-of-s...,Preparation of single-cell suspension from mou...,Preparation of single-cell suspension from mou...,Finely dissect the pancreas into small fragmen...,<no data>,1. Finely dissect the pancreas into small frag...,Pancreas tissue; blade (for dissection); Colla...

# 테이블1: t_protocol_metadata
- columns: protocol_id(PK), url, title

In [3]:
table_metadata = df[["protocol_sid", "url", "title"]]
table_metadata

,protocol_sid,url,title
0,0,https://www.protocols.io/view/ventral-midbrain...,Ventral midbrain dopaminergic (mDA) Neuron Dif...
1,1,https://www.protocols.io/view/transformation-p...,Transformation Protocol for Targeted Homologou...
2,2,https://www.protocols.io/view/an-end-to-end-wo...,An end-to-end workflow for GD2 immunofluoresce...
3,3,https://www.protocols.io/view/optimizing-genet...,Optimizing Genetic Modification in Agrobacteri...
4,4,https://www.protocols.io/view/multi-seq-barcod...,MULTI-Seq Barcoding and Library Preparation
...,...,...,...
4985,4985,https://www.protocols.io/view/transmission-ele...,Transmission electron microscopy of fibroblasts
4986,4986,https://www.protocols.io/view/scqers-library-p...,scQers library preparation
4987,4987,https://www.protocols.io/view/scatac-seq-on-me...,scATAC-seq on mEBs
4988,4988,https://www.protocols.io/view/protocol-for-mai...,Protocol for Maintaining iPSC Cultures
4989,4989,https://www.protocols.io/view/preparation-of-s...,Preparation of single-cell suspension from mou...

In [4]:
# t_protocol_metadata 테이블1에 대한 csv파일생성
table_metadata.to_csv("t_protocol_metadata_Cell.csv", index=False)

# 테이블2: t_protocol_materials
- columns: materials_sid(PK), protocol_id(FK => t_protocol_metadata), materials

In [5]:
table_materials = df[["protocol_sid", "materials"]]
table_materials

      protocol_sid                                          materials
0                0                                             %s%s
1                1  Auxenochlorella protothecoides cells1.5 mL Gra...
2                2  Plastic/metallic warePipette tips for battery-...
3                3  Reagents:LB medium Kanamicyn 50 mg/mlSterile 1...
4                4                                     Reagents:%s%s
...            ...                                                ...
4985          4985                                          <no data>
4986          4986                                          <no data>
4987          4987                                          <no data>
4988          4988  Reagents for iPS culture:- StemMACS™ iPS-Brew ...
4989          4989  Pancreas tissue; blade (for dissection); Colla...

[4990 rows x 2 columns]

In [6]:
# materials_sid(PK) 설정
table_materials = table_materials.reset_index().rename(columns={'index': 'materials_sid'})
table_materials

,materials_sid,protocol_sid,materials
0,0,0,%s%s
1,1,1,Auxenochlorella protothecoides cells1.5 mL Gra...
2,2,2,Plastic/metallic warePipette tips for battery-...
3,3,3,Reagents:LB medium Kanamicyn 50 mg/mlSterile 1...
4,4,4,Reagents:%s%s
...,...,...,...
4985,4985,4985,<no data>
4986,4986,4986,<no data>
4987,4987,4987,<no data>
4988,4988,4988,Reagents for iPS culture:- StemMACS™ iPS-Brew ...
4989,4989,4989,Pancreas tissue; blade (for dissection); Colla...

In [7]:
# t_protocol_materials 테이블2에 대한 csv파일생성
table_materials.to_csv("t_protocol_materials_Cell.csv", index=False)

# 테이블3: t_protocol_references
- columns: references_sid(PK), protocol_id(FK), reference

In [8]:
table_references = df[["protocol_sid", "reference"]]
table_references

      protocol_sid                                          reference
0                0  Kim TW, Piao J, Koo SY, Kriks S, Chung SY, Bet...
1                1  1. Moseley et al. Production of lipids and ter...
2                2                                          <no data>
3                3  Kámán-Tóth E, Pogány M, Dankó T, Szatmári Á, B...
4                4  McGinnis CS, Patterson DM, Winkler J, Conrad D...
...            ...                                                ...
4985          4985                                          <no data>
4986          4986                                          <no data>
4987          4987                                          <no data>
4988          4988  Chen Y, Tristan CA, Chen L, Jovanovic VM, Mall...
4989          4989                                          <no data>

[4990 rows x 2 columns]

In [9]:
# materials_sid(PK) 설정
table_references = table_references.reset_index().rename(columns={'index': 'reference_sid'})
table_references

,reference_sid,protocol_sid,reference
0,0,0,"Kim TW, Piao J, Koo SY, Kriks S, Chung SY, Bet..."
1,1,1,1. Moseley et al. Production of lipids and ter...
2,2,2,<no data>
3,3,3,"Kámán-Tóth E, Pogány M, Dankó T, Szatmári Á, B..."
4,4,4,"McGinnis CS, Patterson DM, Winkler J, Conrad D..."
...,...,...,...
4985,4985,4985,<no data>
4986,4986,4986,<no data>
4987,4987,4987,<no data>
4988,4988,4988,"Chen Y, Tristan CA, Chen L, Jovanovic VM, Mall..."
4989,4989,4989,<no data>

In [10]:
# t_protocol_reference 테이블3에 대한 csv파일생성
table_references.to_csv("t_protocol_references_Cell.csv", index=False)